### PR TITLE
initial work on multipart requests, issue #8

### PR DESCRIPTION
**Pull request by vosmith**
Here is the initial work for performing multipart post requests. added to the API are:

    func (c *Collector) PostMultipartRaw(URL string, requestData map[string][]byte) error
    func (r *Request) PostMultipartRaw(URL string, requestData map[string][]byte) error

Internally, `scrape` was modified to support custom headers and a helper function for fomatting the multipart request body was also added.

An example can be found in `examples/multipart.go`

### CODE REVIEW

**Comment by asciimoo** [comment]
Good PR, thanks!
Wouldn't be simply `PostMultipart` a better name instead of `PostMultipartRaw`? What is the meaning of "raw" here?

**Comment by vosmith** [comment]
I used `raw` to follow the precedent set by the `PostRaw` method where the payload is a `[]byte` as opposed to a string.  I'm not too attached to it though.

**Comment by asciimoo** [comment]
`PostRaw` is `raw` because it receives "raw" data and not a structured one. `PostMultipart(Raw)`'s parameter is a key-value data structure which is not "raw" to me. ..And `PostMultipart` is shorter =)

**Comment by vosmith** [comment]
No problem, will make that change right now

**Pull request merged**
